---

- name: Install redis
  yum:
    name: redis
    state: present

- name: Install php-pecl-redis
  yum:
    name: php-pecl-redis
    state: present

- name: Start redis service
  service:
    name: redis
    state: started
    enabled: yes