---

- name: "Install zsh"
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - zsh
      - wget
      - git

- name: Change shell
  shell: chsh -s /bin/zsh vagrant

- name: "get oh-my-zsh"
  get_url:
    url: https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh
    dest: /tmp/oh-my-zsh-install.sh
    mode: '0755'

- name: Install oh-my-zsh
  shell: /tmp/oh-my-zsh-install.sh
  become: yes
  become_user: vagrant

- name: Copy template file
  template:
    src: zshrc.j2
    dest: ~/.zshrc
