---
# These tasks install laravel.

- name: Install laravel
  shell: /usr/local/bin/composer global require laravel/installer
  become: yes
  become_user: vagrant

- name: make laravel project
  command: /usr/local/bin/composer create-project --prefer-dist laravel/laravel src
  become: yes
  become_user: vagrant
  args:
    chdir: "{{basedir}}/{{project}}"

- name: copy laravel .env file
  template:
    src: laravel.env.j2
    dest: "{{basedir}}/{{project}}/src/.env"

- name: Create a symbolic link
  file:
    src: "{{basedir}}/{{project}}/src"
    dest: "{{basedir}}/{{project}}/live"
    state: link

- name: PATH settings
  become: yes
  become_user: vagrant
  shell: "{{ item }}"
  args:
    chdir: /home/vagrant
  loop:
    - echo >> ~/.bash_profile
    - echo echo 'dir changed to {{basedir}}/{{ project }}/src' >> ~/.bash_profile
    - echo 'cd {{basedir}}/{{ project }}/src' >> ~/.bash_profile