---

- name: create /etc/httpd/conf.d/{{project}}.conf
  template:
    src: vhost.conf.j2
    dest: /etc/httpd/conf.d/{{project}}.conf

- name: create /etc/httpd/conf.d/{{project}}-ssl.conf
  template:
    src: vhost.ssl.conf.j2
    dest: /etc/httpd/conf.d/{{project}}-ssl.conf

- name: Copy star.wiebekn.dev.crt
  copy:
    src: star.wiebekn.dev.crt
    dest: /etc/pki/tls/certs/

- name: Copy star.wiebekn.dev.key
  copy:
    src: star.wiebekn.dev.key
    dest: /etc/pki/tls/private/

# <VirtualHost _default_:443>
- name: Ensure SSL Default site is not running on 443
  lineinfile:
    path: /etc/httpd/conf.d/ssl.conf
    regexp: '^\<VirtualHost\ \_default\_'
    line: "<VirtualHost _default_:8443>"

- name: Ensure SSL Default site is not running on 443
  lineinfile:
    path: /etc/httpd/conf.d/ssl.conf
    regexp: '^SSLCertificateFile'
    line: "SSLCertificateFile /etc/pki/tls/certs/star.wiebekn.dev.crt"

- name: Ensure SSL Default site is not running on 443
  lineinfile:
    path: /etc/httpd/conf.d/ssl.conf
    regexp: '^SSLCertificateKeyFile'
    line: "SSLCertificateKeyFile /etc/pki/tls/private/star.wiebekn.dev.key"

- name: composer install
  composer:
    command: install
    working_dir: "{{basedir}}/{{project}}/src"
    no_dev: no

#- name: create database tables.
#  command: php artisan migrate
#  args:
#    chdir: {{basedir}}/{{project}}/src
#
#- name: fill database with test data.
#  command: php artisan db:seed
#  args:
#    chdir: {{basedir}}/{{project}}/src

- name: Allow httpd to access storage
  sefcontext:
    target: '{{basedir}}/{{project}}/src/(storage/.*)?'
    setype: httpd_sys_rw_content_t
    state: present

- name: Allow httpd to access bootstap/cache
  sefcontext:
    target: '{{basedir}}/{{project}}/src/bootstrap/(cache/.*)?'
    setype: httpd_sys_rw_content_t
    state: present

- name: Apply new SELinux file context to filesystem
  command: restorecon -irv {{basedir}}/{{project}}/*

- name: check md5 of AppServiceProvider
  stat:
    path: "{{basedir}}/{{project}}/src/app/Providers/AppServiceProvider.php"
    checksum_algorithm: md5
    get_checksum: yes
  register: AppServiceProvider

- name: Copy AppServiceProvider.php
  copy:
    src: AppServiceProvider.php
    dest: "{{basedir}}/{{project}}/src/app/Providers/"
  when: AppServiceProvider.stat.checksum == '2472f6584237b1d5f7e91e450bebefa5'

- name: restart httpd
  service:
    name: httpd
    enabled: yes
    state: restarted
