---

- name: Download Node.js v10 repository installation script
  get_url:
    url: https://rpm.nodesource.com/setup_10.x
    dest: /tmp/setup_10.sh
    mode: 777

- name: run the nodejs installation repository
  shell: /tmp/setup_10.sh

- name: Install nodejs
  yum:
    name: nodejs
    state: present